## Linear Algebra

In [ ]:
import numpy as np
from pprint import pprint

In [18]:
# scalar
a = 34
print("Scalar: ", a)
# vector
b = np.array([1,2,3])
print("Vector: ", b)
# matrix
C = np.array([[1,2,3], [4,5,6]])
print(f"Matrix:\n {C}")
# tensor
D = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(f"Tensor:\n {D}")

Scalar:  34
Vector:  [1 2 3]
Matrix:
 [[1 2 3]
 [4 5 6]]
Tensor:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [19]:
# Transport matrix
print("Transposed Matrix:\n", C.T)

Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


In [25]:
# Matrix addition
def add_matrices(A: np.array, B: np.array, scalar_a : int = 1, scalar_b : int = 1) -> np.array:
    if (A.shape == B.shape):
        C = np.add(scalar_a * A, scalar_b * B)
        return C
    else:
        print("Matrices not of same shape")
        return None

In [26]:
add_matrices(C, D, 1, 2)

Matrices not of same shape


In [27]:
E = np.array([[3,2,1], [6,5,4]])
add_matrices(C, E, -1, 2)

array([[ 5,  2, -1],
       [ 8,  5,  2]])

In [ ]:
# adding scalar to matrix
print(C+2)

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [6 7 8]]


In [30]:
# vector product
c = np.array([3,4,5])
print(np.dot(b, c))

26


In [37]:
# matrix multiplication
def mult_matrices(A: np.array, B: np.array) -> np.array:
    if (A.shape[1] == B.shape[0]):
        C = A @ B # same as np.dot(A, B) and np.matmul(A, B)
        return C
    else:
        print("Number of columns of 1st matrix should be equal to number of rows of 2nd matrix")
        return None
X = np.array([[1,2], [3,4], [5,6]])
Y = np.array([[1,2,3,4], [4,5,6,7]])
print(mult_matrices(X, Y))
print(mult_matrices(Y, X))

[[ 9 12 15 18]
 [19 26 33 40]
 [29 40 51 62]]
Number of columns of 1st matrix should be equal to number of rows of 2nd matrix
None


In [44]:
# matrix multiplication is distributive over addition
Z = np.array([[4,3,2,1], [7,6,5,4]])
print(np.all(
    np.equal(
        mult_matrices(X, Y+Z),
        mult_matrices(X, Y)+mult_matrices(X, Z)
        )))

True


In [45]:
# matrix multiplication is associative
Z = np.array([[1,2], [2,1], [1,2], [2,1]])
print(
    np.all(
        np.equal(
            mult_matrices(X, mult_matrices(Y, Z)), 
            mult_matrices(mult_matrices(X, Y), Z)
        )))

True


In [49]:
# matrix multiplication is not commutative

X = np.array([[1,2], [3,4], [5,6]])
Y = np.array([[1,2,3], [4,5,6]])

K = mult_matrices(X, Y)
L = mult_matrices(Y, X)

if (K.shape == L.shape):
    if(np.all(np.equal(K, L))):
        print("Matrices are equal")
    else:
        print("Matrices are not equal")
else:
    print("Matrices of different shapes cannot be compared for equality")

Matrices of different shapes cannot be compared for equality


In [ ]:
# dot product of vectors is commutative
# also, 1-D arrays in NumPy have no orientation. for e.g. a.shape == a.T.shape = (4,) 
b = np.array([12,2,3,5])
c = np.array([3,4,5,7])
print(np.all(np.equal(np.dot(b,c),np.dot(b,c.T))))
print(np.all(np.equal(np.dot(b, c), np.dot(c, b))))

True
True


In [ ]:
# transpose of product of matrices is product of transposes in reverse order
X = np.array([[1,2], [3,4], [5,6]])
Y = np.array([[1,2,3,4], [4,5,6,7]])
print(np.all(np.equal(np.dot(X, Y).T, np.dot(Y.T, X.T))))

True


In [58]:
# system of linear equations can be represeted as dot product of matrix and vector
A = np.array([[1,2], [3,4]])
x = np.array([[1],[3]])
b = np.dot(A,x)
print(b)

[[ 7]
 [15]]


In [60]:
# identity matrix
I = np.eye(4)
print(I)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


Inverse of matrix $A$ is defined as $A^{-1}$ such that $A^{-1}A=I$
In $Ax=b$ we can write
$$A^{-1}Ax=A^{-1}b$$
$$I_nx=A^{-1}b$$
$$x=A^{-1}b$$

In [61]:
# The system of linear equations can be solved by using the inverse of the matrix
# but inverse exists only for square matrices and not all square matrices have inverse. 
# such matrices are called singular matrices
x = np.dot(np.linalg.inv(A), b)
print(x)

[[1.]
 [3.]]


$Ax=b$ can have no solution, one solution, or infinitely many solutions. 

If it has more than one solutions, then infinitely many solutions can be constructed from linear combinations of those two - hence if more than one exists, it has to be infinite.

Now, $Ax=b$ and $A^{-1}b=x$. This is only possible if for a given x, exactly one b exists. If there is no b, or infinitely many bs, then $A^{-1}$ cannot exist

$Ax=\sum_i x_i A_{:,i}$ which can be visualised as each column of A specifying a direction from origin and $x_i$ determining how far to travel in that direction. Cumulatively it leads us to point b.
$\sum_i x_i A_{:,i}$ is called a **linear combination**. 

In general, set of points obtainable by all linear combinations of vectors $\{v_i\}$, i.e. $\sum_i c_i v^{(i)}$, is called the **span** of those vectors.

In $Ax=b$, **span** of all columns of $A$ is called the **range** of $A$; and $b$ must be in the range of $A$ for it to be a solution.

Now $A \in \mathbb{R}^{(m \times n)}$ since it has $m$ rows and $n$ columns. Each of the $n$ columns is a column vector of dimension $m$. For $Ax=b$ to hold, where $b \in \mathbb{R}^m$, the $n$ column vectors must allow for at least $m$ movements, or degrees of freedom, so that any vector in $b$ can be reached. Thus number of column vectors >= dimension of b, or $n \ge m$. This is **necessary but not sufficient** for range of $A$ to contain every $b$; if some of the vectors are linerarly dependent on each other, a degree of freedom is lost.

If $A$ has at least $m$ linearly independent vectors, then this is sufficient for range of $A$ to span $b$. But since each vector is of dimension $m$, it is not possible for more than $m$ vectors to be linearly independent. Thus, the number of linearly independent vectors is exactly equal to $m$

Thus, $A$ has exactly $m$ linearly independent vectors and thus $n=m$ and $A$ is a **Square Matrix**

If some of the vectors among the $m$ vectors are linearly dependent then $A$ is a **Singular Matrix**

In conclusion, $A$ should be a non-singular square matrix for $Ax=b$ to hold.

We have already established that $x = A^{-1}y$ and thus $A^{-1}$ exists only for square, non-singular matrices.

Also the left inverse $(A^{-1}A=I_n)$ and right inverse $(AA^{-1}=I_n)$ of a square matrix are the same.

### Norms

norm = size of vector

properties of a norm
- $f(x)=0 \implies x=0$
- $f(x+y) \le f(x) + f(y)$
- $f(\alpha x) = |\alpha| f(x)$

$L^P$ norm of vector $x$ = ${(\sum_i x_i^P)}^{(1/P)}$

most common is $L^2$ norm = $\sqrt{\sum_i x_i^2}$
For matrices, it is called **Frobenius Norm** ${||A||}_F=\sqrt{\left( A_{i,j}^2 \right)}$

square of $L^2$ norm 
- useful because derivative w.r.t. every term depends only on that term
- problem between 0 and 1 as it moves very slowly in that region

between 0 and 1, practice is to use $L^1$ norm = $\sum_i|x_i|$

sometime number of non-zero elements in a vector is mistakenly called $L^0$ norm, but it is not a norm

$L^{\infty}$ norm, also known as **max norm** $x_{\infty}= max{|x_i|}$

In [70]:
# norm of a vector
v = np.array([-3,-4])
print(np.linalg.norm(v))
# Lˆ5 norm
print(np.linalg.norm(v, ord=5))
# Lˆ1 norm
print(np.linalg.norm(v, ord=1))
# Lˆ\infty norm
print(np.linalg.norm(v, ord=np.inf))

5.0
4.174027662897746
7.0
4.0


### Useful Matrices

#### Diagnonal Matrices
$D_{i,j}=0 \quad \forall \quad i \ne j$

$diag(v)$ is a diagonal matrix with diagonal entries being elements of $v$

Multiplying by diagonal matrix is computationally efficient. $diag(v)x=v \odot x$

Inverting a diagonal martix is computationally efficient. Inverse exists only if all diagonal entries are non-zero. 

$diag(v)^{-1} = diag({[1/v_1,1/v_2 ...1/v_n]}^T)$

In [75]:
# creating a diagonal matrix from a vector
print(np.diag([1,2,3]))

v = np.array([1,2,3])
w = np.array([4,5,6])
print(np.diag(v))

print(np.diag(v) @ w)

# multiplying a diagonal matrix with a vector is same as multiplying 
# the vector elementwise with the diagonal elements of the matrix
print(np.all(np.equal(np.diag(v) @ w, v * w)))

[[1 0 0]
 [0 2 0]
 [0 0 3]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]
[ 4 10 18]
True


#### Symmetric Matrices

$A=A^T$

In [78]:
# Symmetric matric illustration - A is not symmetric while B is symmetric
A = np.array([[1,2], [3,4]])
B = np.array([[5,6], [6,7]])
# np.allclose is used for floating point numbers. Used here for illustration.
print(np.allclose(A, A.T))
# B is symmetric matrix since B = B transposed.
print(np.all(np.equal(B, B.T)))

False
True


#### Unit Vector

Theoretically unit vector is one for which $norm(v)=1$, norm as per definition

usually it is the $L^2$ norm. Hence, unit vector is one for which $||x||=1$

In [82]:
x = np.array([[1],[0]])
y = np.array([[1],[1]])
def check_unit(x: np.array) -> bool:
    return np.allclose(np.linalg.norm(x), 1)
print(check_unit(x))
print(check_unit(y))

True
False


#### Orthogonal Vectors

Two vectors are orthogonal if dot product $x^Ty=0$

#### Orthonomal Vectors

Two vectors are orthonormal if they are unit vectors and also orthogonal to each other

#### Orthogonal Matrix

In which all column vectors are mutually orthonormal and all row vectors also mutually orthonormal

If this is so, then given $Q = [v_1, v_2, ...]$, 

$$
Q^TQ = 
\begin{bmatrix}
v_1^T \\
v_2^T \\
...
\end{bmatrix}
\begin{bmatrix}
v_1 & v_2 & ...
\end{bmatrix}
=
\begin{bmatrix}
v_1^Tv_1 & v_1^Tv_2 & ...\\
v_2^Tv_1 & v_2^Tv_2 & ...\\
...
\end{bmatrix}
$$

but since all vectors are mutually orthonormal 
$$
\begin{align}
v_i^Tv_j &= 1 \quad \forall i=j \\
&= 0 \quad \forall i \ne j \\
\end{align}
$$
Thus, $Q^TQ=I_n$ is another way of defining Orthogonal matrices. 

In [88]:
# Orthogonal and Orthonormal vectors, Orthogonal matrix
def check_orthogonal_vectors(x: np.array, y: np.array) -> bool:
    return np.allclose(np.dot(x.T, y), 0)

def check_orthonormal_vectors(x: np.array, y: np.array) -> bool:
    return check_unit(x) and check_unit(y) and check_orthogonal_vectors(x, y)

def check_orthogonal_matrix(A: np.array) -> bool:
    return np.allclose(np.dot(A.T, A), np.eye(A.shape[1]))

a = np.array([1/np.sqrt(2),1/np.sqrt(2)])
b = np.array([-1/np.sqrt(2),1/np.sqrt(2)])
print(a)
print(b)
print(check_orthogonal_vectors(a,b))
print(check_orthonormal_vectors(a,b))

[0.70710678 0.70710678]
[-0.70710678  0.70710678]
True
True


### Eigendecomposition

analogous to prime factorization of integers

For matrix A and vector v, if $Av=\lambda v$, then $v$ is eigenvector and $\lambda$ is eigenvalue

if $v$ is eigenvector, then $\alpha v$ is also eigenvector for $\alpha \in \mathbb{R}, \alpha \ne 0$ and has the same eigenvalue. Thus it is usual to look only for unit eigenvectors.

If $V$ is matrix of all $n$ eigenvectors of $A$ (i.e. $V=[v_1, v_2...v_n]$) then $A=V diag(\lambda) V^{-1}$ is called the **eigendecomposition** of $A$

Not all matrices have eigenvectors and eigenvalues. Sometimes eigenvalues can be complex numbers.

But every real symmetric matrix can be decomposed as below, with only real eigenvectors and real eigenvalues.
$$A=Q\Lambda Q^T$$
where $Q$ is an orthogonal matrix of eigenvectors of $A$ and $\Lambda$ is a diagonal matrix. Conventionally, the eigenvalues in $\Lambda$ are written in descending order.

The **eigendecomposition**, even for a real symmetric matrix, need not be unique. If two eigenvectors share the same eigenvalue then any other vector in their span is also a potential eigenvector. In general, eigendecomposition is unique only if all eigenvalues are unique.

In [106]:
# we take a symmetric real-valued matrix.
A = np.array([[1,2], [2,3]])
# we get its eigenvalues. Note that eigh works only for symmetric matrices 
# and is more efficient than eig which works for any square matrix.
# eigh by default returns the eigenvalues in ascending order.
L = np.linalg.eigh(A).eigenvalues
# we get the eigenvectors also
Q = np.linalg.eigh(A).eigenvectors
print(f"Eigenvalues: {L}")
print(f"Eigenvectors: {Q}")
# we get the diagonal matrix of eigenvalues and check if A = Q @ diag(L) @ Q.T
print(np.diag(L))
print(np.allclose(A, Q @ np.diag(L) @ Q.T))

Eigenvalues: [-0.23606798  4.23606798]
Eigenvectors: [[-0.85065081  0.52573111]
 [ 0.52573111  0.85065081]]
[[-0.23606798  0.        ]
 [ 0.          4.23606798]]
True


A matrix $A$ is a transformation machine — it takes vectors as input and produces transformed vectors as output. To visualize what $A$ does to 2D space, consider plotting all unit vectors: they form a perfect circle. After applying $A$ to every one of them, the circle becomes an ellipse, revealing that 
> $A$ stretches space unevenly

more in the direction of eigenvector $v_1$ (scaled by $\lambda_1$) and less in the direction of $v_2$ (scaled by $\lambda_2$). 

This is the core idea — 
> eigenvectors are the special directions that A doesn't rotate, only scales, and the eigenvalues are the scaling factors. 

Formally, Av = λv: multiplying an eigenvector by the matrix is identical to just multiplying it by a scalar. The resulting ellipse encodes everything about the transformation — its elongation reflects the ratio of eigenvalues, and its orientation reflects where the eigenvectors point.

### Singular Value Decomposition (SVD)

All matrices do not have an eigendecomposition, for e.g. non-suare matrices.
But all matrices have an SVD. SVD is defined as $A=UDV^T$. If $A$ is $m \times n$ then
- $U$ is orthogonal square matrix ($m \times m$) and its columns are called **left singular vectors** of $A$. These are also the eigenvectors of $AA^T$
- $V$ is orthogonal square matrix ($n \times n$) and its columns are called **right singular vectors** of $A$. These are also the eigenvectors of $A^TA$
- $D$ is $m \times n$ diagonal matrix and its diagonal elements are called **singular values** of $A$. These are also the square roots of the eigenvalues of $AA^T$ and $A^TA$

In [123]:
# we can do singular value decomposition of a matrix by using np.linalg.svd in numpy
A = np.array([[1,2], [3,4]])
left_singular_vectors=np.linalg.svd(A).U
right_singular_vectors=np.linalg.svd(A).Vh.conj().T
singular_values=np.linalg.svd(A).S

print(f"Left singular vectors:\n {left_singular_vectors}")
print(f"Right singular vectors:\n {right_singular_vectors}")
print(f"Singular values:\n {singular_values}")

# left_singular vectors are eigenvectors of A @ A.T, 
# but since eigenvectors are not unique we may get different eigenvectors
# and below test might fail.
S = np.linalg.eig(A @ A.T).eigenvectors
print(f"left singular vectors are eigenvectors of A.AT: {np.allclose(left_singular_vectors, S)}")
# But we can check the subspace of left singular vectors and eigenvectors of A @ A.T 
# are same by checking if their projections are same
print(f"""Subspaces of left singular vectors and eigenvectors of A.AT are same: 
      {np.allclose(left_singular_vectors @ left_singular_vectors.T, S @ S.T)}""")
# right_singular vectors are eigenvectors of A.T @ A
T = np.linalg.eig(A.T @ A).eigenvectors
# similar to what we did for left singular vectors, we can compare the subspaces.
print(f"""Subspaces of right singular vectors and eigenvectors of A.T@A are same: 
      {np.allclose(right_singular_vectors @ right_singular_vectors.T, T @ T.T)}""")

# Finally for the eigenvalues, the singular values are square root of eigenvalues of A.T @ A and A @ A.T.
# For comparison, we must ensure both lists are sorted in a similar way
print(f"""Eigenvalues of A.AT match squares of singular values: 
      {np.allclose(np.sort(np.square(singular_values)), 
                   np.sort(np.linalg.eig(A @ A.T).eigenvalues))}""")

Left singular vectors:
 [[-0.40455358 -0.9145143 ]
 [-0.9145143   0.40455358]]
Right singular vectors:
 [[-0.57604844  0.81741556]
 [-0.81741556 -0.57604844]]
Singular values:
 [5.4649857  0.36596619]
left singular vectors are eigenvectors of A.AT: False
Subspaces of left singular vectors and eigenvectors of A.AT are same: 
      True
Subspaces of right singular vectors and eigenvectors of A.T@A are same: 
      True
Eigenvalues of A.AT match squares of singular values: 
      True


### Moore-Penrose Pseudoinverse

For $Ax=b$ a clean solution exists when $A$ is a square matrix. But this may not always be the case.
- If $A$ is taller than wide, we have overspecified system of equations which may not have any solution
- If $A$ is wider than tall, we have underspecified system which may have more than one solutions

**Moore-Penrose Pseudoinverse** allows us to get to the most sensible possibility of proceeding in both these cases.
- In overspecified cases when there is no solution, the pseudoinverse allows us to get $x$ where $Ax$ is as close as possible to $y$ in terms of the euclidean norm ${||Ax-y||}_2$
- In underspecified cases when there are more than one solutions, it allows us to get the solution with the minimum euclidean norm ${||x||}_2$ among all



Mathematically, using eigendecomposition $A=UDV^T$ and hence $A^{-1}=VDU^T$

But in cases where $A^{-1}$ does not exist, we get the moore-penrose pseudoinverse as $A^+=VD^+U^T$

Everything is the same except $D$ where $D^+$ is determined by taking reciprocal of all non-zero diagonal elements $1/d_{i,i}$ and using $0$ instead of $1/0$ for all 0 entries.

In [144]:
# below code illustrates the calculation of moore-penrose pseudoinverse
# and compares it to direct determination using np.linalg.pinv
A=np.array([[1,2], [2,4]])

left_singular_vectors, singular_values, right_singular_vectors_transpose = np.linalg.svd(A)

moore_penrose_diagonal_matrix = [1/d if d > 1.e-10 else 0 for d in singular_values]

moore_penrose_pseudoinverse = right_singular_vectors_transpose \
    @ np.diag(moore_penrose_diagonal_matrix) \
    @ left_singular_vectors.T

print(f"Computed Moore-Penrose Pseudoinverse is same as from function: \
      {np.allclose(moore_penrose_pseudoinverse, np.linalg.pinv(A))}")

Computed Moore-Penrose Pseudoinverse is same as from function:       True


### Trace of a Matrix

$Tr(A)=\sum_{i} A_{i,i}$ i.e. sum of diagonal entries

Interesting properties of trace that come useful when solving expressions
- ${||A||}_2=\sqrt{Tr(AA^T)}$
- $Tr(A)=Tr(A^T)$
- $Tr(ABC)=Tr(BCA)=Tr(ACB)$ order doesn't matter
- $Tr(AB)=Tr(BA)$ even if $A \in \mathbb{R}^{m \times n}$ and $B \in \mathbb{R}^{n \times m}$ are of different order

In [155]:
A=np.array([[1,2], [3,4]])
trace_A = np.trace(A)
# for non-square matrices, trace is sum of diagonal elements upto min(rows, columns)
B=np.array([[1,2], [3,4], [5,6]])
print(f"Trace of B: {np.trace(B)}")

print(f"Frobenius Norm of matrix = SQRT(Trace(A X A_transpose) : \
      {np.allclose(np.linalg.norm(A), np.sqrt(np.trace(A.T @ A)))}")

print(f"Trace of matrix = Trace of transpose : {np.allclose(np.trace(A), np.trace(A.T))}")

B=np.array([[-1,-2], [-3,-4]])
C=np.array([[1,0], [0,2]])

print(f"Trace of product of matrices is invariant under cyclic permutations: \
      {np.allclose(np.trace(A @ B @ C), np.trace(C @ A @ B))}")

Trace of B: 5
Frobenius Norm of matrix = SQRT(Trace(A X A_transpose) :       True
Trace of matrix = Trace of transpose : True
Trace of product of matrices is invariant under cyclic permutations:       True


### Determinant

It is the product of all eigenvalues of a matrix and maps any matrix to a scalar

Determinant controls how much space is contracted or expanded on multiplication by the matrix

In [159]:
A = np.array([[1,2], [3,4]])

# note that np.multiply needs two arguments and then does elementwise multiplication.
# np.multiply.reduce takes product of all elements in the array 
# and is used here to get the product of all eigenvalues.
#
# Also the determinant and eigenvalue products are floating point numbers and may not be exactly equal. 
# Hence we use np.allclose for comparison.

print(f"Determinant is product of eigenvalues of A : \
      {np.allclose(np.linalg.det(A),np.multiply.reduce(np.linalg.eig(A).eigenvalues))}")

Determinant is product of eigenvalues of A :       True


### Principal Component Analysis (Derivation)

${x_1, x_2... x_m}$ are m points (vectors) in $\mathbb{R}^n$ space
We need lossy compression (to save storage/memory) to *encode* $x_i \in \mathbb{R}^n$ to $c_i \in \mathbb{R}^l$. Compression is easier, but PCA is defined by the decoding function that maps back  or *reconstructs* $c_i$ to $x_i$

Let $x=g(c)$ be defined through decoding matrix $D \in \mathbb{R}^{(n \times l)}$ so that $g(c)=Dc$
$g(c)$ should be such that the decoded value is as close to the original $x$ as possible.

Thus we are trying to find the optimal $c^*$ for $x$ such that 
$$c^* = {arg\: min}_{c}({||x-g(c)||}_2)$$
Now we can substitute $L_2$ with square of $L_2$ so that
$$
\begin{align}
c^* &= {arg\: min}_{c}({||x-g(c)||}_2^2) \\
&={arg\: min}_{c}({(x-g(c))}^T(x-g(c))) \\
&={arg\: min}_{c}((x^T-g(c)^T)(x-g(c))) \\
&={arg\: min}_{c}(x^Tx-x^Tg(c)-g(c)^Tx+g(c)^Tg(c))) \text{  (distributive property)}\\ 
&={arg\: min}_{c}(x^Tx-2x^Tg(c)+g(c)^Tg(c)) \quad (x^Tg(c) \text{ is a scalar, hence equals its transpose)}\\
&={arg\: min}_{c}(-2x^Tg(c)+g(c)^Tg(c)) \quad (x^Tx \text{ does not depend upon c)}\\
&={arg\: min}_{c}(-2x^TDc+c^TD^TDc) \quad \text{substituting } g(c)=Dc \\
&={arg\: min}_{c}(-2x^TDc+c^TI_lc) \quad \text{since } D \text{ is orthogonal and has unit norm}\\
&={arg\: min}_{c}(-2x^TDc+c^Tc)
\end{align}
$$

To solve this, we use Vector calculus where $\nabla_c(f(c))=0$ to get $c={arg\:min}_cf(c)$
$$
\begin{align}
\nabla_c(-2x^TDc+c^Tc)&=0 \\
-2D^Tx+2c&=0 \\
c&=D^Tx \\
\end{align}
$$

Thus we get the **encoding function** (or algorithm) simply as $f(x) = D^Tx$

The decoding or reconstruction function is then simply $r(x)=g(f(x))=DD^Tx$

Thus we need to now choose the appropriate $D$ and for that we again apply the constraint that distance between reconstructed $x$ and original $x$ must be minimum. We need to this element wise for each element of $D$

Thus, $D^* = {arg\:min}_{D}\sqrt{\sum_{i,j} {\left({x^{(i)}_j-r(x^{(i)}_j)} \right)}^2}$ subject to $D^TD=I_l$

Let's first start with $l=1$ so that $D$ is just a single vector $d$

Then, $d^*={arg\:min}_{d}\sum_i {{||x^{(i)}-dd^Tx^{(i)}||}^2_2}$ subject to ${||d||}_2=1$

This can be rewritten as $d^*={arg\:min}_{d}\sum_i {{||x^{(i)}-d^Tx^{(i)}d||}^2_2}$ for more elegance, subject to ${||d||}_2=1$

Now $d^Tx^{(i)}$ is a scalar and hence its own transpose, we get $d^*={arg\:min}_{d}\sum_i {{||x^{(i)}-x^{(i)T}dd||}^2_2}$ subject to ${||d||}_2=1$

If we stack all the $x^{(i)}$s into a matrix we get $X \in \mathbb{R}^{m \times n}$

and then we can get rid of the summation and rewrite as 
$$
\begin{align}
d^*&={arg\:min}_{d}{{||X-Xdd^T||}^2_F} \\
&={arg\:min}_{d}{Tr \left( {(X-Xdd^T)}^T (X-Xdd^T)\right)} \because X_F=\sqrt{Tr(XX^T)}\\
&={arg\:min}_{d}{Tr(X^TX-X^TXdd^T-dd^TX^TX+dd^TX^TXdd^T)} \text{ (distributive law)}\\
&={arg\:min}_{d}{Tr(X^TX)-Tr(X^TXdd^T)-Tr(dd^TX^TX)+Tr(dd^TX^TXdd^T)} \\
&={arg\:min}_{d}{-Tr(X^TXdd^T)-Tr(dd^TX^TX)+Tr(dd^TX^TXdd^T)} \text{ need only terms with d} \\
&={arg\:min}_{d}{-2Tr(X^TXdd^T)+Tr(dd^TX^TXdd^T)} \text{ since Trace is invariant to rearrangement}\\
&={arg\:min}_{d}{-2Tr(X^TXdd^T)+Tr(X^TXdd^T)} \because dd^T=1 \\
&={arg\:min}_{d}{-Tr(X^TXdd^T)} \\
&={arg\:max}_{d}{Tr(X^TXdd^T)} \\
&={arg\:max}_{d}{Tr(d^TX^TXd)}
\end{align}
$$

This can be solved using eigendecomposition. 

Specifically, optimal d is given by eigenvector of $X^TX$ corresponding to the largest eigenvalue

